version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless@3.33.0
  pre_build:
    commands:
      - npm install --silent --no-progress
      - npm run build
  build:
    commands:
      - sls deploy --verbose
  post_build:
    commands: 
      - echo "run tests here"
  